plugins:
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

atom_feed:
  hide: true

locale: fi

defaults:
  - scope:
      path: ""
    values:
      layout: single
      toc: true
      toc_sticky: true
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
